### ISSUE TITLE
The output of CustomData for Cue Detection

### ISSUE THREAD

**Issue by xga0** [adityak6798/Transformers-For-Negation-and-Speculation#2]
Hi Aditya,

Thank you for sharing your code! I ran into a problem when using CustomData to test the Cue Detection subtask. I don't know why, the length of my output is different from the length of the input. 

![Screen Shot 2020-10-09 at 5 41 43 PM](https://user-images.githubusercontent.com/10688079/95633940-bda36780-0a56-11eb-8d49-de6c13aa0cf9.png)

As shown in the screenshot above, my input sentence has five words, but the output has 18 labels. In contrast, using CustomData for Scope Resolution will output the correct results. 

Thanks!

**Comment by adityak6798** [comment]
Fixed this.
